name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for murderface-pets? We'd love to hear it.

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature or improvement you'd like to see.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why?
      description: What problem does this solve or what RP scenario does it enable?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds or considered other approaches?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, examples from other servers, config suggestions, etc.
